# Generated by Django 2.0.13 on 2019-03-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webside', '0002_profile_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sum',
        ),
        migrations.AddField(
            model_name='profile',
            name='antallratet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='sumkarma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='sumratings',
            field=models.IntegerField(default=0),
        ),
    ]
