# Generated by Django 2.0.13 on 2019-03-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webside', '0003_auto_20190314_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
