# Generated by Django 2.1.5 on 2019-02-20 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webside', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
