# Generated by Django 2.0.13 on 2019-03-19 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Webside', '0005_auto_20190319_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade_loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('giver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_giver', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_given', to='Webside.Loan')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Trade',
            new_name='Trade_request',
        ),
    ]
