# Generated by Django 2.0.13 on 2019-03-28 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Webside', '0006_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='trade_loan',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trade_request',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
