# Generated by Django 2.0.13 on 2019-03-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webside', '0006_auto_20190319_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade_loan',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_given', to='Webside.Loan'),
        ),
        migrations.AlterField(
            model_name='trade_request',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_given', to='Webside.Post'),
        ),
    ]
