# Generated by Django 2.1.5 on 2019-02-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webside', '0008_remove_loan_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment2',
            old_name='post',
            new_name='loan',
        ),
    ]
