# Generated by Django 2.0.13 on 2019-03-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webside', '0008_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
