# Generated by Django 2.0.13 on 2019-03-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webside', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='issue_alternative',
            field=models.TextField(null=True),
        ),
    ]
