# Generated by Django 2.0.13 on 2019-03-28 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webside', '0009_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Webside.Community'),
        ),
    ]
