# Generated by Django 2.0.13 on 2019-02-27 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webside', '0010_auto_20190227_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Webside.Community'),
        ),
    ]
