# Generated by Django 2.0.13 on 2019-03-12 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webside', '0012_post_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Webside.Community')),
            ],
        ),
    ]
