# Generated by Django 2.0.13 on 2019-03-12 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webside', '0013_pickcommunity_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reporting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gets_reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
