# Generated by Django 2.0.13 on 2019-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webside', '0015_auto_20190312_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment2',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
